# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/projectvivado/morse_code/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/projectvivado/morse_code/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/pnmin/Downloads/Morse_Code_Encoder_Basys3-master/Morse_Code_Encoder_Basys3-master/Vivado2018.2_project_file/morse_code_encoder/morse_code_encoder.srcs/sources_1/new/morse_encoder.v
read_xdc C:/Users/pnmin/Downloads/Morse_Code_Encoder_Basys3-master/Morse_Code_Encoder_Basys3-master/source_codes/PINS.xdc
set_property used_in_implementation false [get_files C:/Users/pnmin/Downloads/Morse_Code_Encoder_Basys3-master/Morse_Code_Encoder_Basys3-master/source_codes/PINS.xdc]

synth_design -top morse_encoder -part xc7a35tcpg236-1
write_checkpoint -noxdef morse_encoder.dcp
catch { report_utilization -file morse_encoder_utilization_synth.rpt -pb morse_encoder_utilization_synth.pb }
